### ISSUE TITLE
ProviderNotRegistered: github

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [getsentry/sentry-auth-github#12]
```
ProviderNotRegistered: github
  File "celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "sentry/tasks/check_auth.py", line 77, in check_auth_identity
    provider = auth_provider.get_provider()
  File "sentry/models/authprovider.py", line 45, in get_provider
    return manager.get(self.provider, **self.config)
  File "sentry/auth/manager.py", line 21, in get
    raise ProviderNotRegistered(key)
```

**Comment by dcramer** [comment]
You don't have the package installed in whatever process is throwing this error. Likely you didn't restart the server after installing the package

**Comment by Ilya-Kuchaev** [comment]
I do. I've already configured it. I can even login with github. This error appears it Internal project.

**Comment by dcramer** [comment]
You didn't restart the worker process, or you didn't install it there, I promise you.

**Comment by Ilya-Kuchaev** [comment]
Here is the Worker's with -l DEBUG option output:

```
6/15/2016 3:06:33 PM[1;34m[2016-06-15 12:06:33,513: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fa4817c0b90> (args:('sentry.tasks.store.preprocess_event', 'c5fefd4f-6051-4027-948d-14ab5b850571', [], {'start_time': 1465992393.49987, 'cache_key': 'e:1cc494cab4164839b0ce833531d0988f:1'}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'events', u'exchange': 'default'}, 'expires': None, u'hostname': 'celery@26a17738fd70', 'task': 'sentry.tasks.store.preprocess_event', 'callbacks': None, u'correlation_id': 'c5fefd4f-6051-4027-948d-14ab5b850571', 'errbacks': None, 'timelimit': (65, 60), 'taskset': None, 'kwargs': {'start_time': 1465992393.49987, 'cache_key': 'e:1cc494cab4164839b0ce833531d0988f:1'}, 'eta': None, u'reply_to': '1f776572-6c4c-3f07-a539-6aa5437bab08', 'id': 'c5fefd4f-6051-4027-948d-14ab5b850571', u'headers': {}}) kwargs:{})[0m
6/15/2016 3:06:33 PM[2016-06-15 12:06:33,513: INFO/MainProcess] Task sentry.tasks.store.preprocess_event[fcb9f8bc-bfee-4c72-8b03-96834c638f1c] succeeded in 0.00988323311321s: None
6/15/2016 3:06:33 PM[1;34m[2016-06-15 12:06:33,515: DEBUG/MainProcess] Task accepted: sentry.tasks.store.preprocess_event[c5fefd4f-6051-4027-948d-14ab5b850571] pid:21[0m
6/15/2016 3:06:33 PM[1;31m[2016-06-15 12:06:33,516: ERROR/MainProcess] Task sentry.tasks.check_auth_identity[ca1c0ff4-9acd-47aa-b5dd-f8c1dee5cded] raised unexpected: ProviderNotRegistered(u'github',)
6/15/2016 3:06:33 PMTraceback (most recent call last):
6/15/2016 3:06:33 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
6/15/2016 3:06:33 PM    R = retval = fun(*args, **kwargs)
6/15/2016 3:06:33 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
6/15/2016 3:06:33 PM    return self.run(*args, **kwargs)
6/15/2016 3:06:33 PM  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
6/15/2016 3:06:33 PM    result = func(*args, **kwargs)
6/15/2016 3:06:33 PM  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/check_auth.py", line 77, in check_auth_identity
6/15/2016 3:06:33 PM    provider = auth_provider.get_provider()
6/15/2016 3:06:33 PM  File "/usr/local/lib/python2.7/site-packages/sentry/models/authprovider.py", line 45, in get_provider
6/15/2016 3:06:33 PM    return manager.get(self.provider, **self.config)
6/15/2016 3:06:33 PM  File "/usr/local/lib/python2.7/site-packages/sentry/auth/manager.py", line 21, in get
6/15/2016 3:06:33 PM    raise ProviderNotRegistered(key)
6/15/2016 3:06:33 PMProviderNotRegistered: github[0m
6/15/2016 3:06:33 PM[2016-06-15 12:06:33,531: INFO/MainProcess] Received task: sentry.tasks.store.save_event[98018ce8-fda8-4d21-9440-22ab35c66b80]
6/15/2016 3:06:33 PM[1;34m[2016-06-15 12:06:33,531: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fa4817c0b90> (args:('sentry.tasks.store.save_event', '98018ce8-fda8-4d21-9440-22ab35c66b80', [], {'start_time': 1465992393.49987, 'cache_key': 'e:1cc494cab4164839b0ce833531d0988f:1', 'data': None}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'events', u'exchange': 'default'}, 'expires': None, u'hostname': 'celery@26a17738fd70', 'task': 'sentry.tasks.store.save_event', 'callbacks': None, u'correlation_id': '98018ce8-fda8-4d21-9440-22ab35c66b80', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {'start_time': 1465992393.49987, 'cache_key': 'e:1cc494cab4164839b0ce833531d0988f:1', 'data': None}, 'eta': None, u'reply_to': 'dd0e8e6c-b2b3-36d8-b6d9-1325df71ed2b', 'id': '98018ce8-fda8-4d21-9440-22ab35c66b80', u'headers': {}}) kwargs:{})[0m
6/15/2016 3:06:33 PM[1;34m[2016-06-15 12:06:33,533: DEBUG/MainProcess] Task accepted: sentry.tasks.store.save_event[98018ce8-fda8-4d21-9440-22ab35c66b80] pid:22[0m
```

**Comment by dcramer** [comment]
This would indicate the worker processes do not have the extension installed. It must be installed in all environments.

**Comment by Ilya-Kuchaev** [comment]
Oh... I see. I've updated the docker images and it works.
